config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :rides
  
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  
  root 'welcome#index'

end

app/models/companionship.rb
class Companionship < ActiveRecord::Base
end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  def index
    @rides = Ride.all
    @user = User.find(session[:user_id])
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    @user = User.where(:name => params[:signin][:name]).first
    if @user && @user.authenticate(params[:signin][:password])
      session[:user_id] = @user.id
      redirect_to rides_path
    else
      flash[:error] = "Sorry."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to rides_path, notice: 'User was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>You'll Never Ride Alone</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% unless session[:user_id] %> 
              <li><a data-toggle="modal" data-target="#logInModal">
                Log In
              </a>
              </li>
            <% else %>
              <li>
              <%= link_to "Log Out", signout_path, method: :delete %>
              </li>
            <% end %>
          <!-- Button trigger modal -->
          <li><a data-toggle="modal" data-target="#signUpModal">
            Sign Up
          </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
<div class="container">
  <div class="row">
    <div class="col-xs-9"></div>
    <div class="col-xs-3"></div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="signUpModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">
        <%= render 'users/signup_form' %>
      </div>

    </div>
  </div>
</div>
<div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="logInLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="logInLabel">Log In</h4>
      </div>
      <div class="modal-body">
        <%= render 'sessions/new' %>
      </div>

    </div>
  </div>
</div>
</body>
</html>

app/views/rides/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3><%= @user.name %> Profile</h3>
      <h3>Create Ride</h3>
    </div>
    <div class="col-xs-9">
      <h2>List of Rides</h2>
      <ul>
        <%= @rides.each do |ride| %>
        <li>ride.starting_city</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_signup_form.html.erb
<%= form_for :user, url: users_path, html: {class: "form"} do |f| %>

  <ul class="zero list-unstyled">
    <li>
      <p class="form-label">
        Name
      </p>
      <div class="form-input">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </li>
    <br>
      <p class="form-label">
        Email
      </p>
      <div class="form-input">
        <%= f.text_field :email, class: "form-control" %>
      </div>
    </li>
    <br>
    <li>
      <p class="form-label">
        Password
      </p>
      <div class="form-input">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </li>
    <br>
    <li>
      <%= f.submit "Sign Up!", :class => "btn btn-primary" %>
    </li>
    <br>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'signup_form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1><span class="label label-primary">New User</span></h1>

<%= render 'signup_form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div id ='homepage_body'>

</div>